#ifndef XBOXBUTTONTYPES_H
#define XBOXBUTTONTYPES_H

#ifdef FOREACH_BBUTTON
#undef FOREACH_BBUTTON
#endif

#ifdef FOREACH_ABUTTON
#undef FOREACH_ABUTTON
#endif

#define FOREACH_BBUTTON(BUTTON)\
        BUTTON(XBB_DPAD_UP)\
        BUTTON(XBB_DPAD_DOWN)\
        BUTTON(XBB_DPAD_LEFT)\
        BUTTON(XBB_DPAD_RIGHT)\
        BUTTON(XBB_START)\
        BUTTON(XBB_BACK)\
        BUTTON(XBB_LEFT_THUMB)\
        BUTTON(XBB_RIGHT_THUMB)\
        BUTTON(XBB_LEFT_SHOULDER)\
        BUTTON(XBB_RIGHT_SHOULDER)\
        BUTTON(XBB_A)\
        BUTTON(XBB_B)\
        BUTTON(XBB_X)\
        BUTTON(XBB_Y)\
        BUTTON(XBB_TOTAL)\

#define FOREACH_ABUTTON(BUTTON)\
        BUTTON(XAB_LEFT_THUMB_X)\
        BUTTON(XAB_RIGHT_THUMB_X)\
        BUTTON(XAB_LEFT_THUMB_Y)\
        BUTTON(XAB_RIGHT_THUMB_Y)\
        BUTTON(XAB_LEFT_TRIGGER)\
        BUTTON(XAB_RIGHT_TRIGGER)\
        BUTTON(XAB_TOTAL)\

#define GENERATE_ENUM(ENUM) ENUM,

enum Xbox_BButtons
{
    FOREACH_BBUTTON(GENERATE_ENUM)
};

enum Xbox_AButtons
{
    FOREACH_ABUTTON(GENERATE_ENUM)
};

#endif