/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class Asset : IMeta {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Asset(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.Asset_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Asset obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public string GetName() {
    string ret = SharpMochaPINVOKE.Asset_GetName(swigCPtr);
    return ret;
  }

  public string GetAssetType() {
    string ret = SharpMochaPINVOKE.Asset_GetAssetType(swigCPtr);
    return ret;
  }

  public uint GetUseCounter() {
    uint ret = SharpMochaPINVOKE.Asset_GetUseCounter(swigCPtr);
    return ret;
  }

  public uint GetId() {
    uint ret = SharpMochaPINVOKE.Asset_GetId(swigCPtr);
    return ret;
  }

}

}
