/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class AudioManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AudioManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void PlayAll() {
    SharpMochaPINVOKE.AudioManager_PlayAll(swigCPtr);
  }

  public void StopAll() {
    SharpMochaPINVOKE.AudioManager_StopAll(swigCPtr);
  }

  public void ResumeAll() {
    SharpMochaPINVOKE.AudioManager_ResumeAll(swigCPtr);
  }

  public void PauseAll() {
    SharpMochaPINVOKE.AudioManager_PauseAll(swigCPtr);
  }

  public void SetMusicVolume(float vol) {
    SharpMochaPINVOKE.AudioManager_SetMusicVolume(swigCPtr, vol);
  }

  public void SetSoundVolume(float vol) {
    SharpMochaPINVOKE.AudioManager_SetSoundVolume(swigCPtr, vol);
  }

  public float GetMusicVolume() {
    float ret = SharpMochaPINVOKE.AudioManager_GetMusicVolume(swigCPtr);
    return ret;
  }

  public float GetSoundVolume() {
    float ret = SharpMochaPINVOKE.AudioManager_GetSoundVolume(swigCPtr);
    return ret;
  }

  public void SetMuteMusic(bool val) {
    SharpMochaPINVOKE.AudioManager_SetMuteMusic(swigCPtr, val);
  }

  public void SetMuteSound(bool val) {
    SharpMochaPINVOKE.AudioManager_SetMuteSound(swigCPtr, val);
  }

  public bool GetMuteMusic() {
    bool ret = SharpMochaPINVOKE.AudioManager_GetMuteMusic(swigCPtr);
    return ret;
  }

  public bool GetMuteSound() {
    bool ret = SharpMochaPINVOKE.AudioManager_GetMuteSound(swigCPtr);
    return ret;
  }

  public static AudioManager getInstance() {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.AudioManager_getInstance();
    AudioManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioManager(cPtr, false);
    return ret;
  }

}

}
