/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class BaseState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BaseState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BaseState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint NumOfManagedObjects() {
    uint ret = SharpMochaPINVOKE.BaseState_NumOfManagedObjects(swigCPtr);
    return ret;
  }

  public uint NumOfUnManagedObjects() {
    uint ret = SharpMochaPINVOKE.BaseState_NumOfUnManagedObjects(swigCPtr);
    return ret;
  }

  public bool IsActive() {
    bool ret = SharpMochaPINVOKE.BaseState_IsActive__SWIG_0(swigCPtr);
    return ret;
  }

  public void IsActive(bool val) {
    SharpMochaPINVOKE.BaseState_IsActive__SWIG_1(swigCPtr, val);
  }

  public gameObjectSlotTable GetManagedObjectsSlotTable() {
    gameObjectSlotTable ret = new gameObjectSlotTable(SharpMochaPINVOKE.BaseState_GetManagedObjectsSlotTable(swigCPtr), false);
    return ret;
  }

}

}
