/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CAnimationController : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CAnimationController(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.CAnimationController_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CAnimationController obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public void SetAnimation(string animName) {
    SharpMochaPINVOKE.CAnimationController_SetAnimation(swigCPtr, animName);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddAnimation(AssetHandle anim) {
    SharpMochaPINVOKE.CAnimationController_AddAnimation(swigCPtr, AssetHandle.getCPtr(anim));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public Animation GetActiveAnimation() {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.CAnimationController_GetActiveAnimation(swigCPtr);
    Animation ret = (cPtr == global::System.IntPtr.Zero) ? null : new Animation(cPtr, false);
    return ret;
  }

  public bool mIsPlaying {
    set {
      SharpMochaPINVOKE.CAnimationController_mIsPlaying_set(swigCPtr, value);
    } 
    get {
      bool ret = SharpMochaPINVOKE.CAnimationController_mIsPlaying_get(swigCPtr);
      return ret;
    } 
  }

  public float mAnimSpeed {
    set {
      SharpMochaPINVOKE.CAnimationController_mAnimSpeed_set(swigCPtr, value);
    } 
    get {
      float ret = SharpMochaPINVOKE.CAnimationController_mAnimSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public AssetHandle mSingleAnim {
    set {
      SharpMochaPINVOKE.CAnimationController_mSingleAnim_set(swigCPtr, AssetHandle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CAnimationController_mSingleAnim_get(swigCPtr);
      AssetHandle ret = (cPtr == global::System.IntPtr.Zero) ? null : new AssetHandle(cPtr, false);
      return ret;
    } 
  }

  public AnimContainer mAnimations {
    set {
      SharpMochaPINVOKE.CAnimationController_mAnimations_set(swigCPtr, AnimContainer.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CAnimationController_mAnimations_get(swigCPtr);
      AnimContainer ret = (cPtr == global::System.IntPtr.Zero) ? null : new AnimContainer(cPtr, false);
      return ret;
    } 
  }

}

}
