/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CArtifactFX : CPostProcess {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CArtifactFX(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.CArtifactFX_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CArtifactFX obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public float mBlockThreshold {
    set {
      SharpMochaPINVOKE.CArtifactFX_mBlockThreshold_set(swigCPtr, value);
    } 
    get {
      float ret = SharpMochaPINVOKE.CArtifactFX_mBlockThreshold_get(swigCPtr);
      return ret;
    } 
  }

  public float mLineThreshold {
    set {
      SharpMochaPINVOKE.CArtifactFX_mLineThreshold_set(swigCPtr, value);
    } 
    get {
      float ret = SharpMochaPINVOKE.CArtifactFX_mLineThreshold_get(swigCPtr);
      return ret;
    } 
  }

}

}
