/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CBoxColliderComponent : ColliderComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CBoxColliderComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.CBoxColliderComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CBoxColliderComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public MochaVec3 GetCenter() {
    MochaVec3 ret = new MochaVec3(SharpMochaPINVOKE.CBoxColliderComponent_GetCenter(swigCPtr), false);
    return ret;
  }

  public CBoxColliderComponent SetCenter(MochaVec3 c) {
    CBoxColliderComponent ret = new CBoxColliderComponent(SharpMochaPINVOKE.CBoxColliderComponent_SetCenter(swigCPtr, MochaVec3.getCPtr(c)), false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MochaVec3 GetHalfExtents() {
    MochaVec3 ret = new MochaVec3(SharpMochaPINVOKE.CBoxColliderComponent_GetHalfExtents(swigCPtr), false);
    return ret;
  }

  public CBoxColliderComponent SetHalfExtents(MochaVec3 halfExtents) {
    CBoxColliderComponent ret = new CBoxColliderComponent(SharpMochaPINVOKE.CBoxColliderComponent_SetHalfExtents(swigCPtr, MochaVec3.getCPtr(halfExtents)), false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
