/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CollisionData : IMeta {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CollisionData(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.CollisionData_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollisionData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public GameObject collidedObj {
    set {
      SharpMochaPINVOKE.CollisionData_collidedObj_set(swigCPtr, GameObject.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CollisionData_collidedObj_get(swigCPtr);
      GameObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new GameObject(cPtr, false);
      return ret;
    } 
  }

  public CPhysics selfCPhy {
    set {
      SharpMochaPINVOKE.CollisionData_selfCPhy_set(swigCPtr, CPhysics.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CollisionData_selfCPhy_get(swigCPtr);
      CPhysics ret = (cPtr == global::System.IntPtr.Zero) ? null : new CPhysics(cPtr, false);
      return ret;
    } 
  }

  public CPhysics collidedObjCPhy {
    set {
      SharpMochaPINVOKE.CollisionData_collidedObjCPhy_set(swigCPtr, CPhysics.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CollisionData_collidedObjCPhy_get(swigCPtr);
      CPhysics ret = (cPtr == global::System.IntPtr.Zero) ? null : new CPhysics(cPtr, false);
      return ret;
    } 
  }

  public Vector3Vector normals {
    set {
      SharpMochaPINVOKE.CollisionData_normals_set(swigCPtr, Vector3Vector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CollisionData_normals_get(swigCPtr);
      Vector3Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector3Vector(cPtr, false);
      return ret;
    } 
  }

  public int numContacts {
    set {
      SharpMochaPINVOKE.CollisionData_numContacts_set(swigCPtr, value);
    } 
    get {
      int ret = SharpMochaPINVOKE.CollisionData_numContacts_get(swigCPtr);
      return ret;
    } 
  }

  public bool isA {
    set {
      SharpMochaPINVOKE.CollisionData_isA_set(swigCPtr, value);
    } 
    get {
      bool ret = SharpMochaPINVOKE.CollisionData_isA_get(swigCPtr);
      return ret;
    } 
  }

}

}
