/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class ComponentVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<Component>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ComponentVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ComponentVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ComponentVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SharpMochaPINVOKE.delete_ComponentVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ComponentVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Component element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Component this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Component[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Component[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Component[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Component> global::System.Collections.Generic.IEnumerable<Component>.GetEnumerator() {
    return new ComponentVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new ComponentVectorEnumerator(this);
  }

  public ComponentVectorEnumerator GetEnumerator() {
    return new ComponentVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ComponentVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Component>
  {
    private ComponentVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ComponentVectorEnumerator(ComponentVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Component Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Component)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    SharpMochaPINVOKE.ComponentVector_Clear(swigCPtr);
  }

  public void Add(Component x) {
    SharpMochaPINVOKE.ComponentVector_Add(swigCPtr, Component.getCPtr(x));
  }

  private uint size() {
    uint ret = SharpMochaPINVOKE.ComponentVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = SharpMochaPINVOKE.ComponentVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    SharpMochaPINVOKE.ComponentVector_reserve(swigCPtr, n);
  }

  public ComponentVector() : this(SharpMochaPINVOKE.new_ComponentVector__SWIG_0(), true) {
  }

  public ComponentVector(ComponentVector other) : this(SharpMochaPINVOKE.new_ComponentVector__SWIG_1(ComponentVector.getCPtr(other)), true) {
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public ComponentVector(int capacity) : this(SharpMochaPINVOKE.new_ComponentVector__SWIG_2(capacity), true) {
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  private Component getitemcopy(int index) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.ComponentVector_getitemcopy(swigCPtr, index);
    Component ret = (cPtr == global::System.IntPtr.Zero) ? null : new Component(cPtr, false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Component getitem(int index) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.ComponentVector_getitem(swigCPtr, index);
    Component ret = (cPtr == global::System.IntPtr.Zero) ? null : new Component(cPtr, false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Component val) {
    SharpMochaPINVOKE.ComponentVector_setitem(swigCPtr, index, Component.getCPtr(val));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(ComponentVector values) {
    SharpMochaPINVOKE.ComponentVector_AddRange(swigCPtr, ComponentVector.getCPtr(values));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public ComponentVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.ComponentVector_GetRange(swigCPtr, index, count);
    ComponentVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new ComponentVector(cPtr, true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Component x) {
    SharpMochaPINVOKE.ComponentVector_Insert(swigCPtr, index, Component.getCPtr(x));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, ComponentVector values) {
    SharpMochaPINVOKE.ComponentVector_InsertRange(swigCPtr, index, ComponentVector.getCPtr(values));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    SharpMochaPINVOKE.ComponentVector_RemoveAt(swigCPtr, index);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    SharpMochaPINVOKE.ComponentVector_RemoveRange(swigCPtr, index, count);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ComponentVector Repeat(Component value, int count) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.ComponentVector_Repeat(Component.getCPtr(value), count);
    ComponentVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new ComponentVector(cPtr, true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    SharpMochaPINVOKE.ComponentVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    SharpMochaPINVOKE.ComponentVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, ComponentVector values) {
    SharpMochaPINVOKE.ComponentVector_SetRange(swigCPtr, index, ComponentVector.getCPtr(values));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(Component value) {
    bool ret = SharpMochaPINVOKE.ComponentVector_Contains(swigCPtr, Component.getCPtr(value));
    return ret;
  }

  public int IndexOf(Component value) {
    int ret = SharpMochaPINVOKE.ComponentVector_IndexOf(swigCPtr, Component.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(Component value) {
    int ret = SharpMochaPINVOKE.ComponentVector_LastIndexOf(swigCPtr, Component.getCPtr(value));
    return ret;
  }

  public bool Remove(Component value) {
    bool ret = SharpMochaPINVOKE.ComponentVector_Remove(swigCPtr, Component.getCPtr(value));
    return ret;
  }

}

}
