/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class Component : IMeta {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Component(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.Component_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Component obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public bool isEnabled() {
    bool ret = SharpMochaPINVOKE.Component_isEnabled(swigCPtr);
    return ret;
  }

  public void setEnabled(bool v) {
    SharpMochaPINVOKE.Component_setEnabled(swigCPtr, v);
  }

  public bool globalEnabled() {
    bool ret = SharpMochaPINVOKE.Component_globalEnabled(swigCPtr);
    return ret;
  }

  [MochaDoNotShow]
  public GameObject gameObject {
    set {
      SharpMochaPINVOKE.Component_gameObject_set(swigCPtr, GameObject.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.Component_gameObject_get(swigCPtr);
      GameObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new GameObject(cPtr, false);
      return ret;
    } 
  }

  [MochaDoNotShow]
  public string myType {
    set {
      SharpMochaPINVOKE.Component_myType_set(swigCPtr, value);
      if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SharpMochaPINVOKE.Component_myType_get(swigCPtr);
      if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public virtual void CopyFrom(Component c) {
    SharpMochaPINVOKE.Component_CopyFrom(swigCPtr, Component.getCPtr(c));
  }

  public void Destroy() {
    SharpMochaPINVOKE.Component_Destroy(swigCPtr);
  }

}

}
