/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CReflectionProbe : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CReflectionProbe(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.CReflectionProbe_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CReflectionProbe obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public bool mStatic {
    set {
      SharpMochaPINVOKE.CReflectionProbe_mStatic_set(swigCPtr, value);
    } 
    get {
      bool ret = SharpMochaPINVOKE.CReflectionProbe_mStatic_get(swigCPtr);
      return ret;
    } 
  }

  public MochaVec3 mProbeBoxDim {
    set {
      SharpMochaPINVOKE.CReflectionProbe_mProbeBoxDim_set(swigCPtr, MochaVec3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CReflectionProbe_mProbeBoxDim_get(swigCPtr);
      MochaVec3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new MochaVec3(cPtr, false);
      return ret;
    } 
  }

}

}
