/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CScript : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CScript(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharpMochaPINVOKE.CScript_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CScript obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  [MochaDoNotShow]
  public bool isBinded {
    set {
      SharpMochaPINVOKE.CScript_isBinded_set(swigCPtr, value);
    } 
    get {
      bool ret = SharpMochaPINVOKE.CScript_isBinded_get(swigCPtr);
      return ret;
    } 
  }

  public AssetHandle scriptAsset {
    set {
      SharpMochaPINVOKE.CScript_scriptAsset_set(swigCPtr, AssetHandle.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CScript_scriptAsset_get(swigCPtr);
      AssetHandle ret = (cPtr == global::System.IntPtr.Zero) ? null : new AssetHandle(cPtr, false);
      return ret;
    } 
  }

  [MochaDoNotShow]
  public string register_id {
    set {
      SharpMochaPINVOKE.CScript_register_id_set(swigCPtr, value);
      if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = SharpMochaPINVOKE.CScript_register_id_get(swigCPtr);
      if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ScriptProperties p {
    set {
      SharpMochaPINVOKE.CScript_p_set(swigCPtr, ScriptProperties.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CScript_p_get(swigCPtr);
      ScriptProperties ret = (cPtr == global::System.IntPtr.Zero) ? null : new ScriptProperties(cPtr, false);
      return ret;
    } 
  }

}

}
