/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class CTransformVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<CTransform>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CTransformVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CTransformVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CTransformVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SharpMochaPINVOKE.delete_CTransformVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public CTransformVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CTransform element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CTransform this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(CTransform[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(CTransform[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, CTransform[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<CTransform> global::System.Collections.Generic.IEnumerable<CTransform>.GetEnumerator() {
    return new CTransformVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CTransformVectorEnumerator(this);
  }

  public CTransformVectorEnumerator GetEnumerator() {
    return new CTransformVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CTransformVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<CTransform>
  {
    private CTransformVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CTransformVectorEnumerator(CTransformVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CTransform Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (CTransform)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    SharpMochaPINVOKE.CTransformVector_Clear(swigCPtr);
  }

  public void Add(CTransform x) {
    SharpMochaPINVOKE.CTransformVector_Add(swigCPtr, CTransform.getCPtr(x));
  }

  private uint size() {
    uint ret = SharpMochaPINVOKE.CTransformVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = SharpMochaPINVOKE.CTransformVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    SharpMochaPINVOKE.CTransformVector_reserve(swigCPtr, n);
  }

  public CTransformVector() : this(SharpMochaPINVOKE.new_CTransformVector__SWIG_0(), true) {
  }

  public CTransformVector(CTransformVector other) : this(SharpMochaPINVOKE.new_CTransformVector__SWIG_1(CTransformVector.getCPtr(other)), true) {
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public CTransformVector(int capacity) : this(SharpMochaPINVOKE.new_CTransformVector__SWIG_2(capacity), true) {
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  private CTransform getitemcopy(int index) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.CTransformVector_getitemcopy(swigCPtr, index);
    CTransform ret = (cPtr == global::System.IntPtr.Zero) ? null : new CTransform(cPtr, false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CTransform getitem(int index) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.CTransformVector_getitem(swigCPtr, index);
    CTransform ret = (cPtr == global::System.IntPtr.Zero) ? null : new CTransform(cPtr, false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CTransform val) {
    SharpMochaPINVOKE.CTransformVector_setitem(swigCPtr, index, CTransform.getCPtr(val));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CTransformVector values) {
    SharpMochaPINVOKE.CTransformVector_AddRange(swigCPtr, CTransformVector.getCPtr(values));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public CTransformVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.CTransformVector_GetRange(swigCPtr, index, count);
    CTransformVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CTransformVector(cPtr, true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CTransform x) {
    SharpMochaPINVOKE.CTransformVector_Insert(swigCPtr, index, CTransform.getCPtr(x));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CTransformVector values) {
    SharpMochaPINVOKE.CTransformVector_InsertRange(swigCPtr, index, CTransformVector.getCPtr(values));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    SharpMochaPINVOKE.CTransformVector_RemoveAt(swigCPtr, index);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    SharpMochaPINVOKE.CTransformVector_RemoveRange(swigCPtr, index, count);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CTransformVector Repeat(CTransform value, int count) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.CTransformVector_Repeat(CTransform.getCPtr(value), count);
    CTransformVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CTransformVector(cPtr, true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    SharpMochaPINVOKE.CTransformVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    SharpMochaPINVOKE.CTransformVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CTransformVector values) {
    SharpMochaPINVOKE.CTransformVector_SetRange(swigCPtr, index, CTransformVector.getCPtr(values));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(CTransform value) {
    bool ret = SharpMochaPINVOKE.CTransformVector_Contains(swigCPtr, CTransform.getCPtr(value));
    return ret;
  }

  public int IndexOf(CTransform value) {
    int ret = SharpMochaPINVOKE.CTransformVector_IndexOf(swigCPtr, CTransform.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(CTransform value) {
    int ret = SharpMochaPINVOKE.CTransformVector_LastIndexOf(swigCPtr, CTransform.getCPtr(value));
    return ret;
  }

  public bool Remove(CTransform value) {
    bool ret = SharpMochaPINVOKE.CTransformVector_Remove(swigCPtr, CTransform.getCPtr(value));
    return ret;
  }

}

}
