/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class FrameController : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FrameController(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FrameController obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public float GetDeltaTime() {
    float ret = SharpMochaPINVOKE.FrameController_GetDeltaTime(swigCPtr);
    return ret;
  }

  public void CapOn(float fps) {
    SharpMochaPINVOKE.FrameController_CapOn(swigCPtr, fps);
  }

  public void CapOff() {
    SharpMochaPINVOKE.FrameController_CapOff(swigCPtr);
  }

  public float FPSMax() {
    float ret = SharpMochaPINVOKE.FrameController_FPSMax(swigCPtr);
    return ret;
  }

  public static FrameController getInstance() {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.FrameController_getInstance();
    FrameController ret = (cPtr == global::System.IntPtr.Zero) ? null : new FrameController(cPtr, false);
    return ret;
  }

  public static float DT() {
    float ret = SharpMochaPINVOKE.FrameController_DT();
    return ret;
  }

}

}
