/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class LayerMask : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LayerMask(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LayerMask obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void AddLayer(LayerMask.Layers layer) {
    SharpMochaPINVOKE.LayerMask_AddLayer(swigCPtr, (int)layer);
  }

  public void RemoveLayer(LayerMask.Layers layer) {
    SharpMochaPINVOKE.LayerMask_RemoveLayer(swigCPtr, (int)layer);
  }

  public int GetLayerMasks() {
    int ret = SharpMochaPINVOKE.LayerMask_GetLayerMasks(swigCPtr);
    return ret;
  }

  public bool IsOnLayer(LayerMask.Layers layer) {
    bool ret = SharpMochaPINVOKE.LayerMask_IsOnLayer(swigCPtr, (int)layer);
    return ret;
  }

  public enum Layers {
    LAYER_0 = 0x1,
    LAYER_1 = 0x2,
    LAYER_2 = 0x4,
    LAYER_3 = 0x8,
    LAYER_4 = 0x10,
    LAYER_5 = 0x20,
    LAYER_NORAYCAST = 0x40,
    LAYER_UI = 0x80,
    LAYER_TOTAL
  }

}

}
