/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public class MochaVec2 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MochaVec2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MochaVec2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MochaVec2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SharpMochaPINVOKE.delete_MochaVec2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

		public MochaVec2(Microsoft.Xna.Framework.Vector2 vec)
		{
			x = vec.X;
            y = vec.Y;
		}
		public static implicit operator MochaVec2(Microsoft.Xna.Framework.Vector2 vec)  // explicit byte to digit conversion operator
		{
			return new MochaVec2(vec);
		}
		public static implicit operator Microsoft.Xna.Framework.Vector2(MochaVec2 vec)  // explicit byte to digit conversion operator
		{
			Microsoft.Xna.Framework.Vector2 tmp = new Microsoft.Xna.Framework.Vector2();
			
			tmp.X = vec.x;
			tmp.Y = vec.y;

			return tmp;
		}
	    
  public MochaVec2() : this(SharpMochaPINVOKE.new_MochaVec2__SWIG_0(), true) {
  }

  public MochaVec2(float x, float y) : this(SharpMochaPINVOKE.new_MochaVec2__SWIG_1(x, y), true) {
  }

  public MochaVec2(SWIGTYPE_p_ConstRealPointer data) : this(SharpMochaPINVOKE.new_MochaVec2__SWIG_2(SWIGTYPE_p_ConstRealPointer.getCPtr(data)), true) {
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_float GetE(uint index) {
    SWIGTYPE_p_float ret = new SWIGTYPE_p_float(SharpMochaPINVOKE.MochaVec2_GetE(swigCPtr, index), false);
    return ret;
  }

  public MochaVec2 Sub() {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Sub__SWIG_0(swigCPtr), true);
    return ret;
  }

  public MochaVec2 Mul(float rhs) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Mul__SWIG_0(swigCPtr, rhs), true);
    return ret;
  }

  public MochaVec2 Div(float rhs) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Div__SWIG_0(swigCPtr, rhs), true);
    return ret;
  }

  public MochaVec2 Add(MochaVec2 rhs) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Add(swigCPtr, MochaVec2.getCPtr(rhs)), true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MochaVec2 Sub(MochaVec2 rhs) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Sub__SWIG_1(swigCPtr, MochaVec2.getCPtr(rhs)), true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Comp(MochaVec2 rhs) {
    bool ret = SharpMochaPINVOKE.MochaVec2_Comp(swigCPtr, MochaVec2.getCPtr(rhs));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool NegComp(MochaVec2 rhs) {
    bool ret = SharpMochaPINVOKE.MochaVec2_NegComp(swigCPtr, MochaVec2.getCPtr(rhs));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MochaVec2 Mul(MochaVec2 rhs) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Mul__SWIG_1(swigCPtr, MochaVec2.getCPtr(rhs)), true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MochaVec2 Div(MochaVec2 rhs) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Div__SWIG_1(swigCPtr, MochaVec2.getCPtr(rhs)), true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set(float x, float y) {
    SharpMochaPINVOKE.MochaVec2_Set(swigCPtr, x, y);
  }

  public void ZeroOut() {
    SharpMochaPINVOKE.MochaVec2_ZeroOut(swigCPtr);
  }

  public MochaVec2 Reflect(MochaVec2 reflectionAxis) {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Reflect(swigCPtr, MochaVec2.getCPtr(reflectionAxis)), true);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddScaledVector(MochaVec2 Vector, float scalar) {
    SharpMochaPINVOKE.MochaVec2_AddScaledVector(swigCPtr, MochaVec2.getCPtr(Vector), scalar);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public float Dot(MochaVec2 rhs) {
    float ret = SharpMochaPINVOKE.MochaVec2_Dot(swigCPtr, MochaVec2.getCPtr(rhs));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float Length() {
    float ret = SharpMochaPINVOKE.MochaVec2_Length(swigCPtr);
    return ret;
  }

  public float LengthSq() {
    float ret = SharpMochaPINVOKE.MochaVec2_LengthSq(swigCPtr);
    return ret;
  }

  public MochaVec2 Normalized() {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Normalized(swigCPtr), true);
    return ret;
  }

  public float Normalize() {
    float ret = SharpMochaPINVOKE.MochaVec2_Normalize(swigCPtr);
    return ret;
  }

  public float AttemptNormalize() {
    float ret = SharpMochaPINVOKE.MochaVec2_AttemptNormalize(swigCPtr);
    return ret;
  }

  public MochaVec2 Negate() {
    MochaVec2 ret = new MochaVec2(SharpMochaPINVOKE.MochaVec2_Negate(swigCPtr), false);
    return ret;
  }

  public bool Valid() {
    bool ret = SharpMochaPINVOKE.MochaVec2_Valid(swigCPtr);
    return ret;
  }

  public void Splat(float value) {
    SharpMochaPINVOKE.MochaVec2_Splat(swigCPtr, value);
  }

  public float x {
    set {
      SharpMochaPINVOKE.MochaVec2_x_set(swigCPtr, value);
    } 
    get {
      float ret = SharpMochaPINVOKE.MochaVec2_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      SharpMochaPINVOKE.MochaVec2_y_set(swigCPtr, value);
    } 
    get {
      float ret = SharpMochaPINVOKE.MochaVec2_y_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_float array {
    set {
      SharpMochaPINVOKE.MochaVec2_array_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.MochaVec2_array_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

}

}
