/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

public enum ParticleBehaviour {
  PB_DEFAULT = 0,
  PB_IMPLOSION,
  PB_EXPLOSION,
  PB_ORBIT,
  PB_3DORBIT,
  TOTAL_BEHAVIOURS
}

}
