/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

	using System;
	using System.Runtime.InteropServices;

	//using MochaDotNET;
	//using System.ComponentModel;

public partial class SetGameObjectPtr : System.IDisposable 
#if SWIG_DOTNET_3
    , System.Collections.Generic.ISet<GameObject>
#endif
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SetGameObjectPtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SetGameObjectPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SetGameObjectPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SharpMochaPINVOKE.delete_SetGameObjectPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SetGameObjectPtr() : this(SharpMochaPINVOKE.new_SetGameObjectPtr__SWIG_0(), true) {
  }

  public SetGameObjectPtr(SetGameObjectPtr other) : this(SharpMochaPINVOKE.new_SetGameObjectPtr__SWIG_1(SetGameObjectPtr.getCPtr(other)), true) {
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint size() {
    uint ret = SharpMochaPINVOKE.SetGameObjectPtr_size(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = SharpMochaPINVOKE.SetGameObjectPtr_empty(swigCPtr);
    return ret;
  }

  public void Clear() {
    SharpMochaPINVOKE.SetGameObjectPtr_Clear(swigCPtr);
  }

  private GameObject getitem(GameObject val) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.SetGameObjectPtr_getitem(swigCPtr, GameObject.getCPtr(val));
    GameObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new GameObject(cPtr, false);
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(GameObject x) {
    SharpMochaPINVOKE.SetGameObjectPtr_setitem(swigCPtr, GameObject.getCPtr(x));
  }

  public bool Contains(GameObject val) {
    bool ret = SharpMochaPINVOKE.SetGameObjectPtr_Contains(swigCPtr, GameObject.getCPtr(val));
    return ret;
  }

  public void Add(GameObject val) {
    SharpMochaPINVOKE.SetGameObjectPtr_Add(swigCPtr, GameObject.getCPtr(val));
    if (SharpMochaPINVOKE.SWIGPendingException.Pending) throw SharpMochaPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Remove(GameObject val) {
    bool ret = SharpMochaPINVOKE.SetGameObjectPtr_Remove(swigCPtr, GameObject.getCPtr(val));
    return ret;
  }

  public global::System.IntPtr create_iterator_begin() {
    global::System.IntPtr ret = SharpMochaPINVOKE.SetGameObjectPtr_create_iterator_begin(swigCPtr);
    return ret;
  }

  public bool is_iterator_good(SWIGTYPE_p_std__setT_GameObject_p_t__iterator swigier) {
    bool ret = SharpMochaPINVOKE.SetGameObjectPtr_is_iterator_good(swigCPtr, SWIGTYPE_p_std__setT_GameObject_p_t__iterator.getCPtr(swigier));
    return ret;
  }

  public GameObject get_next_key(global::System.IntPtr swigiterator) {
    global::System.IntPtr cPtr = SharpMochaPINVOKE.SetGameObjectPtr_get_next_key(swigCPtr, swigiterator);
    GameObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new GameObject(cPtr, false);
    return ret;
  }

  public void destroy_iterator(global::System.IntPtr swigiterator) {
    SharpMochaPINVOKE.SetGameObjectPtr_destroy_iterator(swigCPtr, swigiterator);
  }

}

}
