/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MochaInterface {

public class SharpMocha {
  public static Color WHITE {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.WHITE_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color BLACK {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.BLACK_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color RED {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.RED_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color GREEN {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.GREEN_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color BLUE {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.BLUE_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color YELLOW {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.YELLOW_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color SILVER {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.SILVER_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color LIGHT_STEEL_BLUE {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.LIGHT_STEEL_BLUE_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color CORNFLOWER_BLUE {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.CORNFLOWER_BLUE_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color LIME_GREEN {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.LIME_GREEN_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

  public static Color GREY {
    get {
      global::System.IntPtr cPtr = SharpMochaPINVOKE.GREY_get();
      Color ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color(cPtr, false);
      return ret;
    } 
  }

}

}
